let me = {
    "created_at":"Sun Aug 07 22:31:20 +0000 2022",
    "id":1556407673284861952,
    "id_str":"1556407673284861952",
    "full_text":"RT @i_ameztoy: Extra random image (I):\n\nLets focus in one very specific zone of the western coast -&gt; Longjing District, Taichung #City, #Ta\u2026",
    "truncated":false,
    "display_text_range":[
       0,
       143
    ],
    "entities":{
       "hashtags":[
          {
             "text":"City",
             "indices":[
                132,
                137
             ]
          }
       ],
       "symbols":[
          
       ],
       "user_mentions":[
          {
             "screen_name":"i_ameztoy",
             "name":"Iban Ameztoy",
             "id":3418339671,
             "id_str":"3418339671",
             "indices":[
                3,
                13
             ]
          }
       ],
       "urls":[
          
       ]
    },
    "metadata":{
       "iso_language_code":"en",
       "result_type":"recent"
    },
    "source":"<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
    "in_reply_to_status_id":null,
    "in_reply_to_status_id_str":null,
    "in_reply_to_user_id":null,
    "in_reply_to_user_id_str":null,
    "in_reply_to_screen_name":null,
    "user":{
       "id":3418339671,
       "id_str":"3418339671",
       "name":"Iban Ameztoy",
       "screen_name":"i_ameztoy",
       "location":"",
       "description":"It\u00b4s not all about fancy words, but place always matters. Earth Observer \ud83d\udef0\ud83c\udf0d Now @EU_scienceHub All Views My Own \ud83d\uddfa",
       "url":null,
       "entities":{
          "description":{
             "urls":[
                
             ]
          }
       },
       "protected":false,
       "followers_count":20497,
       "friends_count":2621,
       "listed_count":232,
       "created_at":"Wed Aug 12 17:31:24 +0000 2015",
       "favourites_count":15760,
       "utc_offset":null,
       "time_zone":null,
       "geo_enabled":true,
       "verified":false,
       "statuses_count":8097,
       "lang":null,
       "contributors_enabled":false,
       "is_translator":false,
       "is_translation_enabled":false,
       "profile_background_color":"000000",
       "profile_background_image_url":"http://abs.twimg.com/images/themes/theme1/bg.png",
       "profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme1/bg.png",
       "profile_background_tile":false,
       "profile_image_url":"http://pbs.twimg.com/profile_images/1516525072302981122/2-zDuyTR_normal.jpg",
       "profile_image_url_https":"https://pbs.twimg.com/profile_images/1516525072302981122/2-zDuyTR_normal.jpg",
       "profile_banner_url":"https://pbs.twimg.com/profile_banners/3418339671/1545080943",
       "profile_link_color":"1B95E0",
       "profile_sidebar_border_color":"000000",
       "profile_sidebar_fill_color":"000000",
       "profile_text_color":"000000",
       "profile_use_background_image":false,
       "has_extended_profile":false,
       "default_profile":false,
       "default_profile_image":false,
       "following":false,
       "follow_request_sent":false,
       "notifications":false,
       "translator_type":"none",
       "withheld_in_countries":[
          
       ]
    },
    "geo":null,
    "coordinates":null,
    "place":null,
    "contributors":null,
    "retweeted_status":{
       "created_at":"Sun Aug 07 20:15:13 +0000 2022",
       "id":1556373418915815424,
       "id_str":"1556373418915815424",
       "full_text":"Extra random image (I):\n\nLets focus in one very specific zone of the western coast -&gt; Longjing District, Taichung #City, #Taiwan \n \n#Copernicus #Sentinel2 \ud83d\udef0\ufe0f 2022-08-03 \nFull Size -&gt; https://t.co/39IOoqJZR9 \ud83e\uddd0 https://t.co/rdf21paD5P",
       "truncated":false,
       "display_text_range":[
          0,
          214
       ],
       "entities":{
          "hashtags":[
             {
                "text":"City",
                "indices":[
                   117,
                   122
                ]
             },
             {
                "text":"Taiwan",
                "indices":[
                   124,
                   131
                ]
             },
             {
                "text":"Copernicus",
                "indices":[
                   135,
                   146
                ]
             },
             {
                "text":"Sentinel2",
                "indices":[
                   147,
                   157
                ]
             }
          ],
          "symbols":[
             
          ],
          "user_mentions":[
             
          ],
          "urls":[
             {
                "url":"https://t.co/39IOoqJZR9",
                "expanded_url":"https://flic.kr/p/2nCWhN1",
                "display_url":"flic.kr/p/2nCWhN1",
                "indices":[
                   189,
                   212
                ]
             }
          ],
          "media":[
             {
                "id":1556372372650868738,
                "id_str":"1556372372650868738",
                "indices":[
                   215,
                   238
                ],
                "media_url":"http://pbs.twimg.com/media/FZlYbUoWQAI5xmb.jpg",
                "media_url_https":"https://pbs.twimg.com/media/FZlYbUoWQAI5xmb.jpg",
                "url":"https://t.co/rdf21paD5P",
                "display_url":"pic.twitter.com/rdf21paD5P",
                "expanded_url":"https://twitter.com/i_ameztoy/status/1556373418915815424/photo/1",
                "type":"photo",
                "sizes":{
                   "thumb":{
                      "w":150,
                      "h":150,
                      "resize":"crop"
                   },
                   "large":{
                      "w":2048,
                      "h":1280,
                      "resize":"fit"
                   },
                   "small":{
                      "w":680,
                      "h":425,
                      "resize":"fit"
                   },
                   "medium":{
                      "w":1200,
                      "h":750,
                      "resize":"fit"
                   }
                }
             }
          ]
       },
       "extended_entities":{
          "media":[
             {
                "id":1556372372650868738,
                "id_str":"1556372372650868738",
                "indices":[
                   215,
                   238
                ],
                "media_url":"http://pbs.twimg.com/media/FZlYbUoWQAI5xmb.jpg",
                "media_url_https":"https://pbs.twimg.com/media/FZlYbUoWQAI5xmb.jpg",
                "url":"https://t.co/rdf21paD5P",
                "display_url":"pic.twitter.com/rdf21paD5P",
                "expanded_url":"https://twitter.com/i_ameztoy/status/1556373418915815424/photo/1",
                "type":"photo",
                "sizes":{
                   "thumb":{
                      "w":150,
                      "h":150,
                      "resize":"crop"
                   },
                   "large":{
                      "w":2048,
                      "h":1280,
                      "resize":"fit"
                   },
                   "small":{
                      "w":680,
                      "h":425,
                      "resize":"fit"
                   },
                   "medium":{
                      "w":1200,
                      "h":750,
                      "resize":"fit"
                   }
                }
             }
          ]
       },
       "metadata":{
          "iso_language_code":"en",
          "result_type":"recent"
       },
       "source":"<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
       "in_reply_to_status_id":1554866413155897346,
       "in_reply_to_status_id_str":"1554866413155897346",
       "in_reply_to_user_id":3418339671,
       "in_reply_to_user_id_str":"3418339671",
       "in_reply_to_screen_name":"i_ameztoy",
       "user":{
          "id":3418339671,
          "id_str":"3418339671",
          "name":"Iban Ameztoy",
          "screen_name":"i_ameztoy",
          "location":"",
          "description":"It\u00b4s not all about fancy words, but place always matters. Earth Observer \ud83d\udef0\ud83c\udf0d Now @EU_scienceHub All Views My Own \ud83d\uddfa",
          "url":null,
          "entities":{
             "description":{
                "urls":[
                   
                ]
             }
          },
          "protected":false,
          "followers_count":20497,
          "friends_count":2621,
          "listed_count":232,
          "created_at":"Wed Aug 12 17:31:24 +0000 2015",
          "favourites_count":15760,
          "utc_offset":null,
          "time_zone":null,
          "geo_enabled":true,
          "verified":false,
          "statuses_count":8097,
          "lang":null,
          "contributors_enabled":false,
          "is_translator":false,
          "is_translation_enabled":false,
          "profile_background_color":"000000",
          "profile_background_image_url":"http://abs.twimg.com/images/themes/theme1/bg.png",
          "profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme1/bg.png",
          "profile_background_tile":false,
          "profile_image_url":"http://pbs.twimg.com/profile_images/1516525072302981122/2-zDuyTR_normal.jpg",
          "profile_image_url_https":"https://pbs.twimg.com/profile_images/1516525072302981122/2-zDuyTR_normal.jpg",
          "profile_banner_url":"https://pbs.twimg.com/profile_banners/3418339671/1545080943",
          "profile_link_color":"1B95E0",
          "profile_sidebar_border_color":"000000",
          "profile_sidebar_fill_color":"000000",
          "profile_text_color":"000000",
          "profile_use_background_image":false,
          "has_extended_profile":false,
          "default_profile":false,
          "default_profile_image":false,
          "following":false,
          "follow_request_sent":false,
          "notifications":false,
          "translator_type":"none",
          "withheld_in_countries":[
             
          ]
       },
       "geo":null,
       "coordinates":null,
       "place":null,
       "contributors":null,
       "is_quote_status":false,
       "retweet_count":2,
       "favorite_count":4,
       "favorited":false,
       "retweeted":false,
       "possibly_sensitive":false,
       "lang":"en"
    },
    "is_quote_status":false,
    "retweet_count":2,
    "favorite_count":0,
    "favorited":false,
    "retweeted":false,
    "lang":"en"
 }